# Generated by Django 2.1.7 on 2019-03-23 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0002_palestrante_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacao',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=800),
            preserve_default=False,
        ),
    ]
