# Generated by Django 2.1.7 on 2019-03-23 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0003_pontuacao_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniCursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minicurso', models.CharField(max_length=300)),
                ('ministrante', models.CharField(max_length=300)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mini_curso',
                'verbose_name_plural': 'mini_cursos',
            },
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
