# Generated by Django 2.1.7 on 2019-03-23 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0004_auto_20190323_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontuacaoMinicursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('clareza', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tempo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tema', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('relevancia', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('data', models.DateField(auto_now_add=True)),
                ('minicurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graficos.MiniCursos')),
            ],
            options={
                'verbose_name': 'Pontuação',
                'verbose_name_plural': 'Pontuações',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pontuacaominicursos',
            unique_together={('minicurso', 'email')},
        ),
    ]
