# Generated by Django 2.1.7 on 2019-03-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0005_auto_20190323_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontuacaominicursos',
            options={'verbose_name': 'Pontuação Minicurso', 'verbose_name_plural': 'Pontuações Minicurso'},
        ),
    ]
