# Generated by Django 2.1.7 on 2019-03-31 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0006_auto_20190323_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Avaliação do Evento', 'verbose_name_plural': 'Avaliações do Evento'},
        ),
        migrations.AddField(
            model_name='pontuacaominicursos',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
