# Generated by Django 2.1.7 on 2019-04-11 00:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0009_auto_20190411_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacaominicursos',
            name='pontuacao',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='pontuacaominicursos',
            name='sugestao',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
