# Generated by Django 2.1.7 on 2019-04-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0010_auto_20190411_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacao',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pontuacaominicursos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pontuacaominicursos',
            name='sugestao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
