# Generated by Django 2.1.7 on 2019-04-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficos', '0012_auto_20190411_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minicursos',
            name='ministrante',
        ),
    ]
